A = set(input('A = ').split(','))
B = set(input('B = ').split(','))
print('Intersecţia mulţimilor =', A.intersection(B))
print('Reuniunea mulţimilor =', A.union(B))
print('Diferenţa mulţimilor =', A.difference(B), B.difference(A))